print("Welcome \"Arsh\".")
feeling = input("\nSo, How are you feeling right now?\n\t1. Iman se taro-taza.\n\t2. Kisi Ladki ko ya kisi aise manzar ko dekhne ki talab ki jisse maza aa jae. Aur ye mai sirf aaj bhar aakhri baar dekhunga, aur apni saari khwahish poori kar lunga.\n>>>")
if feeling != "1":
    input("\n\n\n\n\tKya tumko lagta hai ki ye tumhara Aakhri baar hai is gunah ko karte hue?\n6 saal se tum is badnazri ke gunah me mubtala ho.\n Aur agar nafsani khwahisho ke galat istemal ki baat kare to 9 saal ho gae is gunah ke kaam ko karte hue aur tum tab se bas yahi kah rahe ho ki aaj ye mera last time hai.\nMera sawal tumse ye hai ki, Tum is gunah se kab rukoge? kya koi farishta utrega aasman se tumko is gunah se rokne ke liye?\n>>>")
    pass
    input("\n\n\n\n\tKya mai apni Islah karna nahi chahta, kya mujhe sirf doosre ki Islah ki fikr karne ki zaroorat hai, Kya Akhirat me sabse pahle mujhse mere Aamaal ke bare me nahi poocha jaega?\n>>>")
    pass
    ans = input("\n\n\n\n\t Ab meri baat dhyan se suno, ye bahut jyada logic wala aur common sense ka baat hai: \n Aisa duniya me koi shakhsh na paida hua aur na hoga jiski saari khwahishat mukammal taur par is duniya me poori hui ho, To batao ki tumhe kyu lagta hai ki tum aaj apni saari khwahish poori taur par poori kar loge. ya aaj nahi bhi kar paoge tab bhi tumhe aisa kyu lagta hai ki tumhari saari khwahish poori hongi is duniya me.\n Ye kaam to Jannat me hone wala hai ki saari khwahishe, tum jo sochoge poori ho jaengi, lekin uske liye is dhoke ke ghar aur dukh aur takleef ke ghar - \"Duniya\" me thoda sabr karna padega, thoda dukh ko gale lagana padega, Allah ki nafarmani se bachna padega aur Allah ki farmabardari karna padega, uske liye maine pahle se ek routine bana ke rakha hai jis par chalenge to inshaAllah Allah ki nafarmani se bach jaenge, Allah ki farmabardari karne me aasaani hogi, aur mere jimme jiske bhi hukook hai unko Allah ki raza ke liye ada kar paenge. To us routine ke mutabiq abhi tumhara jo kaam hai tumko wo kaam karna chahiye.\n\nTo ab tum humko Routine sb dekh ke batao ki tum kaam me lagne jaa rahe ho ya nahi?\n[y/n] :- ")
    if ans.lower() != "y":
        input("\n\n\n\n\tKya agar hum musalman nahi hote. Mujhe Allah ke ahkamo ka pata nahi hota, ki Allah hame kis tarah dekhna chahte hai. Aurato ko parda karna hai. Aur meri bahan is tarah beparda rahti apni nangi tasweer kheech ke internet me dalti to kya hum ye chahte ki koi meri bahan ko is tarah dekhe.\n>>>")
        pass
        input("\n\n\n\n\tTo ab jabki humko Allah ke ahkaaam ka pata hai. Meri bahno ko bhi pata hai, isliye we aisa kaam nahi karti lekin kisi ke bahan ko ya beti ko ya maa ko ye baat pata nahi hai. to kya hum unki bewakoofi ka faida uthae ya unki galti ka faida uthai aur doosre ki behan doosre ki beti ya doosre ki maa ki nangi tasweer dekhe.\n>>>")
        pass
        input("\n\n\n\n\tTumko kya lagta hai ki tumhare andar ye gunah ki khwahish itni jyada bhari hui hai ki tum is kaam ko chor hi nhi sakte?\nTo meri baat suno: Allah ta'ala ne insaan ke dil me dono kism ke jazbaat aur dono kism ki khwahise rakhi hai, Gunah ki khwahish bhi aur Taqwa ki khwahish bhi, Kabhi gunah ki khwahish bhi paida hoti hai aur kabhi neki ki khwahish paida hoti hai.\n>>>")
        pass
        input("\n\n\n\n\tInsaan me buri khwahisho ki baat kare to do tarah ki khwahishe ubharti hai. ek tarah ki khwahishe aisi hoti hai ki wo is duniya me poori hi nahi ho sakti hai, jaise mai agar chahunga ki mai har waqt khuch rahu, har waqt bas khata rahu, ya sota rahu, ya ghoomta rahu, \nAur ek doosri tarah ki khwahish ye hoti hai ki unko poora karne ki koshish karne se Allah tabarak wa'ta'aala naraz hote hai, jinko karne wala Allah ka nafarman ban jata hai. \nTo kuch kwahish ko majbooran chor do - is wajah se chor diya ki \"kya karu hongi hi nahi poori, is duniya me possible hi nahi hai.\"Aur ek kwahish wo hai ki jinko mahaj Allah ka hukm maanne ke liye, Allah ki ita'at ke khatir, Allah ki nafarmani se bachne ke liye chorna padta hai.Allah ta'ala farmate hai ki \"Jo khwahish ko hamare liye chor raha hai, jiske dil me ye khawf paida hua ki ek din mujhe mere parwardigar ke saamne ja ke khada hona hai, aur is wajah se apni khwahish ko chora, to uska thikana Jannat hai.\"\n>>>")
        pass
        input("\n\n\n\n\tTo bhai zara socho to sahi Mere Allah ne mujhe itne saare nemato se nawaza hai, meri ye Aankh itni badi nemat hai, iske liye mujhe koi paisa nahi kharch karna pada, koi mehnat nahi karna pada, Allah ne mujhe saari duniya ko mujhe dekhne ki ijazat de rakhi hai, har tarah ke ache ache nazaaro ko dekhne ki ijazat de rakhi hai bas chand cheeze aisi hai ki jisse mana farmaya hai ki: Meri is di hui sarkari machine ko is kaam ke andar istemal na karna. To badi Gairat ki baat hai ki us malike haqiki ke di hui is nemat ko mai uski masiyat me istemal karu, usko gussa dilane wale kaamo me istemal karu? Aur ek din mujhse is nemat ke bare me, aur is masiyat wale amal ke baare me, mere malik-e-haqiqi mujhse poochenge bhi.\n>>>")
        pass
        ans2 = input("\n\n\n\n\tTo bhai khwahishe to kabhi bhi poori nahi hongi, ya majbooran is masiyat wale kaam ko choroge ya Allah ke khatir choroge.\n\t\"To meri har khwahish to poori hone wali nahi hai, mai apne is khwahish ko Allah ke liye chorta hu.\"\n\t[y/n]: ")
        if ans2.lower() != "y":
            input("\n\n\n\n\t\tDekho mere bhai ye mera last suggestion hai,: 'Jab koi Allah ka banda apni khwahishat ko Allah tabark wa ta'ala ke liye kuchalne ka irada karta hai, aur us par amal karta hai, to phir Allah tabarak wa ta'atla ki taraf se madad hoti hai.' Allah tabarak wa ta'ala farmate hai - \"Jo ye mujahada karte hai to hum unko jaroor bil jaroor apne rasto par utha kar le jaenge.\" Itni taqeed ke saath Allah ta'ala is cheej ko irshad farmaye hai. ek jagah hajrat wala ne iska tarjuma is tarah bayan kiya hai ki - \"Hum unko haath me utha kar apne rasto par daal denge.\"\n>>>")
        else:
            input("\n\n\n\n\tJazakAllahu-Khair bhai Tumne mere duniya wa aakhirat dono ke nuksan hone bacha liya, \n'Jab koi Allah ka banda apni khwahishat ko Allah tabark wa ta'ala ke liye kuchalne ka irada karta hai, aur us par amal karta hai, to phir Allah tabarak wa ta'atla ki taraf se madad hoti hai.' Allah tabarak wa ta'ala farmate hai - \"Jo ye mujahada karte hai to hum unko jaroor bil jaroor apne rasto par utha kar le jaenge.\" Itni taqeed ke saath Allah ta'ala is cheej ko irshad farmaye hai. ek jagah hajrat wala ne iska tarjuma is tarah bayan kiya hai ki - \"Hum unko haath me utha kar apne rasto par daal denge.\"\n>>>")

    else:
        input("\n\n\n\n\t\tJazakAllahu-Khair\n>>>")

else:
    print("\n\n\n\n\t\tAlhamdulillah!")
